export const FETCH_PAPER_START = 'FETCH_PAPER_START'
export const FETCH_PAPER_SUCCESS = 'FETCH_PAPER_SUCCESS'
export const FETCH_PAPER_FAIL = 'FETCH_PAPER_FAIL'

export const FETCH_SHAPES_START = 'FETCH_FETCH_SHAPES_START'
export const FETCH_SHAPES_SUCCESS = 'FETCH_FETCH_SHAPES_SUCCESS'
export const FETCH_SHAPES_FAIL = 'FETCH_FETCH_SHAPES_FAIL'

export const FETCH_JSONDATA_START = 'FETCH_JSONDATA_START'
export const FETCH_JSONDATA_SUCCESS = 'FETCH_JSONDATA_SUCCESS'
export const FETCH_JSONDATA_FAIL = 'FETCH_JSONDATA_FAIL'
